# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - git remote add public git@github.com:sharpdigital/test-ci.git
          - rm ./README.md
          - git pull public master
          - cp ./index.html ./docs/index.html
          - git add .
          - git commit -m "from bb pipeline"
          - git push public master